### ISSUE TITLE
Junction finding sometimes fails

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#109]
Some annealed oligos don't finish junction determination, unclear why.

https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAAA3KlZqZ4

**Comment by bthuronyi** [comment]
Related? Junction determination sometimes gives #N/A

https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAAA3KlZqZ0

**Comment by santiagochrist** [comment]
The `#ERROR` in Row 1158 is caused by this line, which I isolated and caused some kind of iteration overflow:
`=COMMON_SUBSTRING_FROM_LEFT(1,$CM1158,$CP1158)`

**Comment by santiagochrist** [comment]
> Related? Junction determination sometimes gives #N/A
> 
> https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAAA3KlZqZ0

Misplaced parenthesis near the end of the code. This is what it reads currently:
```
...
TRUE,"USER jct search error!",
TRUE,"jct search error!"))
```
A brief CTRL+F of CC shows that there "jct search error!" message never shows, and it makes sense because a second true condition will never be satisfied. In other words, the `ifs(...)` that encloses all of the code does not have a base case. The code should instead read:
```
...
TRUE,"USER jct search error!"),
TRUE,"jct search error!")
```

**Comment by santiagochrist** [comment]
Documentation:
-
- Function: `COMMON_SUBSTRING_FROM_LEFT(guess_length, source, target)`
- When guess_length is greater than 0, we enter an infinite loop for sequences that have no substring match. It seems that the intended break in the formula does not work, which hasn't been much of a problem for most d entities but we have a few exceptions as seen in this issue.
- When guess_length is less than 0, we manually force the function to return 0 (the "break"), which is what we want. This is useful when assessing the Sheets code, since it manually adjusts the formula to return what we want. However, the Sheets code will take the common substring length of 0 and return this: `"REVERSE COMPLEMENT 2_REVERSE COMPLEMENT 1`
- We need to handle the case of 0 properly, maybe if the length of the common substring is 0 (i.e., does not exist) then return some error message like "no common substring found," rather than just not catching the error and returning `#ERROR!`

**Comment by santiagochrist** [comment]
CSFL:
-
Turns out that a simple check for the `guess_length` was all that was needed for the function to break its recursion. I was not aware that Sheets could keep track of this number incrementing on every iteration, but now that I am it turns out that the solution is very simple:
```
=ifs(
or(guess_length > len(source), guess_length > len(target)), 0, // what was missing - if guess_length is too long, cut the function and return 0
iferror(search(left(source,guess_length+1),target),FALSE),COMMON_SUBSTRING_FROM_LEFT(guess_length+1,source,target),
TRUE,guess_length)
```
Worth talking about the line I deleted:
```
not(iferror(search(left(source,guess_length),target),0)),0, // this line tried to cut the recursion originally, but it always evaluated to false
```
Substituting the deleted line resulted in the same output.

Left Junction Sequence Column:
-
We now handle a simple syntax error that prevents the `#N/A` error and also handle the case where `CSFL` properly returns `0` when there is no substring match.
```
=ifs(
or($M1157="",$N1157="",$AF1157<>TRUE),,
$L1157="anneal",
 let(anneal_len,COMMON_SUBSTRING_FROM_LEFT(1,$CM1157,$CP1157),
 if(anneal_len=0,"USER jct search error!", // 0 case was previously unhandled and returned the entire RCO2_O1 sequence
 trim(lower(left($CP1157,len($CP1157)-anneal_len)))&"_"&trim(DNA_REVERSE_COMPLEMENT(lower(right($CM1157,len($CM1157)-anneal_len)))))),
and(index('Oligos o'!$I$3:$I,xmatch($M1157,'Oligos o'!$B$3:$B))="y",index('Oligos o'!$I$3:$I,xmatch($N1157,'Oligos o'!$B$3:$B))="y"),
 ifs(
  $AH1157="",index('Oligos o'!$X$3:$X,xmatch($M1157,'Oligos o'!$B$3:$B))&"_"&index('Oligos o'!$X$3:$X,xmatch($N1157,'Oligos o'!$B$3:$B)),
  and(iferror(search($CM1157,$AH1157),FALSE),iferror(search($CP1157,$AH1157),FALSE)),
   index('Oligos o'!$X$3:$X,xmatch($M1157,'Oligos o'!$B$3:$B)),
  and(iferror(search($CN1157,$AH1157),FALSE),iferror(search($CO1157,$AH1157),FALSE)),
   index('Oligos o'!$X$3:$X,xmatch($N1157,'Oligos o'!$B$3:$B)),
  TRUE,"USER jct search error!"), // there were two parentheses here originally, which prevented a "base case"
TRUE,"jct search error!")
```

Right Junction Sequence Column:
-
Copied over the code but used different ranges and the `right` instead of `left` functions to get right junctions.
```
=ifs(
or($M1160="",$N1160="",$AF1160<>TRUE),,
$L1160="anneal",
 let(anneal_len,COMMON_SUBSTRING_FROM_LEFT(1,$CM1160,$CP1160),
 if(anneal_len=0,"USER jct search error!",
 trim(lower(right($CM1160,len($CM1160)-anneal_len)))&"_"&trim(DNA_REVERSE_COMPLEMENT(lower(left($CP1160,len($CP1160)-anneal_len)))))),
and(index('Oligos o'!$I$3:$I,xmatch($M1160,'Oligos o'!$B$3:$B))="y",index('Oligos o'!$I$3:$I,xmatch($N1160,'Oligos o'!$B$3:$B))="y"),
 ifs(
  $AH1160="",index('Oligos o'!$AA$3:$AA,xmatch($N1160,'Oligos o'!$B$3:$B))&"_"&index('Oligos o'!$AA$3:$AA,xmatch($M1160,'Oligos o'!$B$3:$B)),
  and(iferror(search($CM1160,$AH1160),FALSE),iferror(search($CP1160,$AH1160),FALSE)),
   index('Oligos o'!$AA$3:$AA,xmatch($N1160,'Oligos o'!$B$3:$B)),
  and(iferror(search($CN1160,$AH1160),FALSE),iferror(search($CO1160,$AH1160),FALSE)),
   index('Oligos o'!$AA$3:$AA,xmatch($M1160,'Oligos o'!$B$3:$B)),
  TRUE,"USER jct search error!"),
TRUE,"jct search error!")
```
This worked on my copy of CC and handled error cases, let me know what you think @bthuronyi!

**Comment by bthuronyi** [comment]
> I was not aware that Sheets could keep track of this number incrementing on every iteration

It's not that it keeps track, it's that the recursion is manipulating the value in between calls, so the nested calls end up running using different values. We just need one of them to eventually return 0 and then that will bubble all the way up to the first call's return value!

**Comment by bthuronyi** [comment]
> // there were two parentheses here originally, which prevented a "base case"
> TRUE,"jct search error!")

Yeah, this kind of thing is a killer especially if it doesn't lead to a formula parse error. Plus, you don't get a lot of help writing the named formula code -- you have to work on it in the main sheet and then paste it over, and it doesn't always work right in that case... anyway, glad it was straightforward to fix!

**Comment by bthuronyi** [comment]
> This worked on my copy of CC and handled error cases, let me know what you think @bthuronyi!

Great! If the outputs are the same for other cases and now handled the errors, that's all we can hope for -- go ahead and implement in main. You'll need to edit the code for the Named Function.
