### ISSUE TITLE
4ml on CC Asst: miniprep tab

### ISSUE THREAD

**Issue by ixf1** [bthuronyi/CloneCoordinate#120]
In CC Asst: miniprep tab, it would be nice to know that 4 ml is required as said on Protocol: Inoculating cultures in a 24-well plate for minipreps.

**Comment by ixf1** [comment]
Add/track culture volume too!

**Comment by bthuronyi** [comment]
"4 mL" should be a new Setting under the Minipreps area -- default culture volume. We need a new user-editable / named range column in Minipreps for "culture volume" with the default displayed above it (as done for other fields). Fill in historical data for existing preps except where notes refer to a different volume. Add volume notification(s) on Asst: Minipreps only where volume(s) don't match the default.

**Comment by santiagochrist** [comment]
Implemented into live CC following review of my CC copy, ready for review @bthuronyi.

Summary:
-
- Created 'Culture Volume' user-inputted column and assigned the 'Minipreps_m_Culture_volume' named range to it.
- Used the code below on Asst: minipreps to pull the user-inputted value for culture volume (default 4 mL):
`=iferror(if($A3<>"",dget('Minipreps m'!$A$2:$DL,W$2,{$A$2;"="&$A3}),""), "")`
- Applied conditional formatting rule to warn the user about a non-default culture volume:
`Apply to range: W3:W194`
`Custom formula is: =AND($W3<>4,$W3<>"")`

**Comment by bthuronyi** [comment]
Coming along! I added units to the column title.

For the "Default" field, remember we are doing these with an array literal formula so that users can copy and paste just the value without needing to paste-as-values. So you would want to do this as in e.g. cell AC1 on Minipreps m.

Similarly, the 4 mL volume must be a Named Range Setting in Settings & admin, not a hard-coded "4". You would want to change that for the Defaults formula but also for the conditional formatting in Asst: Minipreps.

**Comment by bthuronyi** [comment]
While all the culture volumes were set to 4 mL in the new column and this is mostly correct, I checked through the "queue notes" and "purification notes" columns and found a handful of descriptions of using different culture volumes -- these are now entered in the new column.

**Comment by santiagochrist** [comment]
Thank you for the reminder, I have created a new named range in Settings named: settings_mDefaultCultureVolume (currently set to 4).

I will say that the conditional formatting on the assistant tab didn't let me introduce the settings_mDefaultCultureVolume into the custom formula, so it is still hard-coded to 4 there.

Other than that, I placed the array literal on the header, so this issue is mostly fine.

**Comment by bthuronyi** [comment]
Great!

> I will say that the conditional formatting on the assistant tab didn't let me introduce the settings_mDefaultCultureVolume into the custom formula, so it is still hard-coded to 4 there.

Yeah, this is an annoying Sheets thing. You _can_ use it, but you need to reference it using the INDIRECT function:
`=indirect("settings_mDefaultCultureVolume")` will pull the value -- note that the named range is entered as a string.

Make that change and you're all set!
