### ISSUE TITLE
Fixing Minipreps m when the status is "No growth." (It still outputs "Ready to quantify" if I initial/date.)

### ISSUE THREAD

**Issue by ixf1** [bthuronyi/CloneCoordinate#122]
When the Minipreps m status is "No growth," it still outputs "Ready to quantify" if I initial/date. We think there should be some kind of override.

**Comment by santiagochrist** [comment]
Solution: Place the line of code controlling that right below the manual statuses and right above the QC statuses.

```
=if(A753="","",
trim(ifs(
not(Q753),"certify queueing!",
FALSE,"Note: parts of the next block are duplicated in 'Prep from sequence-verified construct?'",
FALSE,"Read manual status assignments from the column that integrates these with any assigned in Sequencing",
CF753="! Conflicting manual statuses assigned to different instances of this mID in Sequencing!",CF753,
regexmatch(CF753,"(don't use)"),CF753,
regexmatch(CF753,"(hold)"),"wait; held"&if(H753=""," (from Sequencing)",""),
AG753="no","stalled - did not grow",
and(AS753<>"",AS753<settings_qcLowMiniprepConcCutoff),"Failed: low conc!",
```

What's very interesting is that after a `regexmatch` of the old statuses with the new ones, it seems that there are 20 ish minipreps that were quantified/purified/proceeded with despite not having grown any colonies :)

m751, m829, m852, m863, m864, m865, m872, m873, m1344, m1345, m1346, m1611, m1646, m1647, m1648, m1707, m1888, m1913, m1914, m1915, m1933, m1934, m2074

<img width="412" alt="Screenshot 2024-08-02 at 10 31 15 AM" src="https://github.com/user-attachments/assets/b09ff184-9c02-4fdb-81e1-2882afe6f393">

An interesting case is m1707, which had the wrong antibiotic or something like that, but placing the code below the antibiotic check (line 50 something of status) would bring back the original bug. With that being said, the code technically deals with it properly since the growth was marked as "no". If we want the antibiotic message to come back (may give more info, who knows) then we can just simply remove the "no" from the dropdown for "Grew?" and leave it blank. @bthuronyi

**Comment by ethanjeon** [comment]
Inserted the "stalled - did not grow" line a bit further down

`
=if(A3345="","",
trim(ifs(
not(Q3345),"certify queueing!",

FALSE,"Note: parts of the next block are duplicated in 'Prep from sequence-verified construct?'",
FALSE,"Read manual status assignments from the column that integrates these with any assigned in Sequencing",
CE3345="! Conflicting manual statuses assigned to different instances of this mID in Sequencing!",CE3345,
regexmatch(CE3345,"(don't use)"),CE3345,
regexmatch(CE3345,"(hold)"),"wait; held"&if(H3345=""," (from Sequencing)",""),
and(AS3345<>"",AS3345<settings_qcLowMiniprepConcCutoff),"Failed: low conc!",
regexmatch(iferror(index(Registry_Manual_status_assignment,xmatch(E3345,Registry_Construct_name))),"[Aa]bandon"),"construct abandoned",
regexmatch(iferror(index(Registry_Manual_status_assignment,xmatch(E3345,Registry_Construct_name))),"(hold)"),"construct held",

AG3345="no","stalled - did not grow",
`
