### ISSUE TITLE
Asst: dsDNA doesn't handle digests properly

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#126]
Asst: dsDNA shows errors for irrelevant fields such as "Oligo 1" when a Digest is selected as the thing to do. We need to sort out whether we're going to handle digests within Asst: dsDNA for v1.0 or not, and if not, ideally show an informative error message when a digest is chosen in the Asst, but at a minimum leave the fields blank.

**Comment by evelynqi** [comment]
I may be wrong but I don't think the regular dsDNA sheet is set up to handle digests properly either... seems that status of dsDNA is determined primarily by the PCR cells -- I didn't check all of them but the status of template is only looking at the PCR template and not the template for digests so it returns that the digest is not ready to do because "template not found".

**Comment by evelynqi** [comment]
But otherwise, I'm thinking in "used by formulas >", we add an iferror to 

=if($A5="","",
ID_TO_WELL(dget('dsDNA d'!$A$2:$CA,'dsDNA d'!$M$2,{$A$2;$A5})))

so that it is

=if($A5="","",
iferror(ID_TO_WELL(dget('dsDNA d'!$A$2:$CA,'dsDNA d'!$M$2,{$A$2;$A5})), "")

This way the oligo cells are "" and the µL values are also "" since it looks at the oligo cell. The informative error could go into the header when sort number exists and the oligo cell is empty with conditional formatting.

**Comment by evelynqi** [comment]
Implemented in https://docs.google.com/spreadsheets/d/1YSqAdAVy6jYu_-Nbnop_aQOGMjjLDXzNKm5-Ur23Pcc/edit?usp=sharing 

Asst: dsDNA sheet (CHANGED D, BQ, BR)

**Comment by evelynqi** [comment]
Notes from B: 
-tie error messages to "digest" status
-keep conditional formatting

**Comment by evelynqi** [comment]
Ready to check for implementation:

Instead of iferror, the error cells are blank due to type of dsDNA being "digest": 

=if($A5="","",
if($BL5="digest", "", ID_TO_WELL(dget('dsDNA d'!$A$2:$CA,'dsDNA d'!$M$2,{$A$2;$A5}))))
_____________________________________________________________
Also, message in header is tied to constructs being a digest and informs them that the assistant sheet does not currently handle digests.

=if(countif($BL3:BL, "digest")>0,"digest not handled in asst sheet currently", "")
_____________________________________________________________
Conditional formatting on the sort # when the type of dsDNA is "digest":
=$BL3="digest"

**Comment by bthuronyi** [comment]
* Added "type" column to Asst: dsDNA to help illustrate different rows - you may want to add a corresponding column in your copy before bringing code over!
* Otherwise looks good, given that, you know, as stated we don't yet support digests!
Go ahead and implement in main CC.

**Comment by evelynqi** [comment]
Implemented! Note: For the informative header, I added it to the same cell with error message when there are duplicate sort #s!

=ifs(
     and(join("",unique(A3:A))<>join("",A3:A),countif($BM3:BM, "digest")>0), "duplicate sort #! also digests not handled in asst sheet currently",
     join("",unique(A3:A))<>join("",A3:A),"duplicate sort #!",
     countif($BM3:BM, "digest")>0,"digest not handled in asst sheet currently",
     TRUE, "")

**Comment by evelynqi** [comment]
Cleaned up message for when we want to add more informative messages in the same cell:

=if(
     join("",unique(A3:A))<>join("",A3:A),"duplicate sort #! ","")
     & if(countif($BM3:BM, "digest")>0,"digest not handled in asst sheet currently","")
