### ISSUE TITLE
STATUS sequencing

### ISSUE THREAD

**Issue by ethanjeon** [bthuronyi/CloneCoordinate#140]
A place to gather and track all sequencing Status-related issues and changes. Part of the larger Issue #64 of auditing all Status formula logic.

**Comment by ethanjeon** [comment]
240709

Extensive revisions implemented, mostly documented under Issue #91.  Rearrangement for experimental chronology, splitting off pre-mixing inputs into a new Queueing Validity Check column, etc.  

Chronology alone was able to fix other issues like #93 - a very promising revision strategy going forward for other Statuses.

**Comment by bthuronyi** [comment]
See #141

**Comment by bthuronyi** [comment]
A few bugs in the current implementation -- probably just a number of things that need to move from Queueing validity check to Status. Anything that can change state between queueing and mixing needs to reside in Status so the messages don't get hidden by the "certify correctly queued".

Cases not handled in Status that need to be (not exhaustive list):

- [x] - oligo not available yet (waiting on order or shipment)
- [x] - mID ran out/volume low
- [x] - mID not done
- [x] - dID not done

- etc

**Comment by bthuronyi** [comment]
- [x] Status should throw an error if "date mixed" is entered but "well for mixed sample" is blank

**Comment by bthuronyi** [comment]
Made some substantial changes, mostly to move a lot of stuff back into Status. Left some of these elements in Queueing validity check too because why not, but they do need to be in Status.

Somewhat streamlined the code around pulling status info for the template -- enclosed the IFS in a LET that gets the status of the source ID, so we can reference it multiple times later.

Sequencing Status now reads from #134 and #138. If needed, that link could be removed without too much trouble. Doesn't look like this is a problem currently, except I did have to change the lookup list "List of construct names for mIDs currently queued for sequencing (where read is not completely done yet):" so it doesn't look at Sequencing Status but instead at whether an alignment has been interpreted -- same result.

**Comment by bthuronyi** [comment]
Remaining tie-ins: #141 and possibly #104.

**Comment by bthuronyi** [comment]
Update: checking #141, it's not actually a Sequencing status issue, but instead about Minipreps "ready to queue sequencing" i.e. when mIDs are flagged to be added to the Sequencing tab.

**Comment by bthuronyi** [comment]
#104 could plausibly involve Sequencing Status, but any change needed would be easy to drop in -- most of the changes here needed to be done around the "ready to mix" step. So, closing this for now as complete enough.
