### ISSUE TITLE
Ligation validation in Assemblies queueing validity

### ISSUE THREAD

**Issue by ethanjeon** [bthuronyi/CloneCoordinate#147]
Towards the end of the code, we have:
`"Ligation","Validation not yet implemented",`

For two-piece ligations, check that both pieces were cut using the same enzymes.

For three or more... maybe for now we just have it output the different enzymes used?  Two-piece ligations should be most common.

**Comment by evelynqi** [comment]
Piece 1 was cut using these enzymes, etc...

**Comment by evelynqi** [comment]
"Parts were cut using multiple REs. Check parts for BsaI NdeI overhangs" and "✓ Junctions verified!" are the two messages that it should currently display. 

https://docs.google.com/spreadsheets/d/1pj3EE8p0EfHMjC5LHxOq8eIBKOBOVIINs4iZcbac9VY/edit?usp=sharing
Queueing validity check (Assemblies Z)

**Comment by evelynqi** [comment]
sort enzymes for part 1 == sort enzymes for part 2, then good, otherwise give part and enzymes

output d part1, e1,e2
d part 2, e1, e2
d part 3...

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1pj3EE8p0EfHMjC5LHxOq8eIBKOBOVIINs4iZcbac9VY/edit?usp=sharing

Assemblies (Z)

I'm very excited about this!! I personally think this is really cool and I'm proud of the amount of time it took to implement... 

It outputs "✓ Junctions verified!" when there are 2 parts and the enzymes of part 1 and part 2 are the same. Otherwise, it outputs, "Junction error: check parts!". 

For multiple part ligations, it says the generic message of "Multiple piece ligation check not available. Check parts." along with the parts and the REs that were used to make the parts. 

Example: 
"Multiple piece ligation check not available. Check parts.
d1283: SapI, BsaI
d1157: SapI, KpnI
d1165: NdeI, XbaI"

Test cases are at the bottom, a957, a958, and a959!

**Comment by bthuronyi** [comment]
I like the implementation! Here are a few comments on the coding implementation:

1. Although the syntax `dsDNA_d_Digest_enzyme1:dsDNA_d_Digest_enzyme2` works to specify a 2-column range, it breaks in the event that the two Named Ranges are moved relative to each other. Instead, use `{dsDNA_d_Digest_enzyme1,dsDNA_d_Digest_enzyme2}` which is equivalent but robust toward moving the columns.
2. You might be using FILTER in a situation where you expect only 1 match. In those situations, it's faster and therefore better practice to use INDEX/XMATCH instead. For example, `filter({dsDNA_d_Digest_enzyme1,dsDNA_d_Digest_enzyme2},dsDNA_d_ID=y)` becomes `index({dsDNA_d_Digest_enzyme1,dsDNA_d_Digest_enzyme2},xmatch(y,dsDNA_d_ID))`. The differences are that XMATCH completes when it finds 1 match AND it's also optimized to work on sorted inputs (which we often use and is the case here). Actually you can even use INDEX( ... , ID_TO_INDEX(y)) which is a special case where the column you're matching against is an ID column. But regular XMATCH is still good.
3. You have some curly braces where they're not required and could be confusing -- `sort({filter(dsDNA_d_Digest_enzyme1:dsDNA_d_Digest_enzyme2,dsDNA_d_ID=y)})` is equivalent to `sort(filter(dsDNA_d_Digest_enzyme1:dsDNA_d_Digest_enzyme2,dsDNA_d_ID=y))` since the FILTER already outputs an array (and so will INDEX if you call it on a 2d array input).

**Comment by bthuronyi** [comment]
There's some more debugging to do as well: see aIDs 1 and 2 in your sheet; a1 gives #N/A! instead of an informative message and a2 gives "junctions verified!" when it should give some kind of error since both d3 and d4 are not digests.

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1pj3EE8p0EfHMjC5LHxOq8eIBKOBOVIINs4iZcbac9VY/edit?usp=sharing
Assemblies (Z)
1. Fixed all coding syntax things mentioned in your comment
2. Added check for if any of the parts are not a digest type to correct for the bugs in a1 and a2 --> if(regexmatch(join(" ",AB3:AI3),"(PCR)|(anneal)"),"Check parts! Not all parts are digests."&"
"&trim(join("
",bycol(P3:W3, lambda(y, if(y<>"", y&": " & bycol(P3:W3, lambda(x,textjoin("", TRUE, index(dsDNA_d_Type,xmatch(y,dsDNA_d_ID))))),"")))))


This will now give message of "Check parts! Not all parts are digests." followed by a list of parts with their corresponding types separated by a new line. 

Example: 
"Check parts! Not all parts are digests.
d1: PCR
d2: PCR"

**Comment by bthuronyi** [comment]
Great work here!

Seems like a few more cases to handle. I changed a1, a2 and a3 again and am not getting expected output.

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/1pj3EE8p0EfHMjC5LHxOq8eIBKOBOVIINs4iZcbac9VY/edit?usp=sharing

We once again seek approval.

**Comment by bthuronyi** [comment]
Looking good. For "One piece ligation!" replace this with "One piece ligation?" because somebody might want to e.g. cut a dimer and ligate it to try to isolate monomer.

Otherwise, go for it!

**Comment by evelynqi** [comment]
Implemented.
