### ISSUE TITLE
Asst: dsDNA needs to respect max samples per block setting

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#154]
The setting "settings_dMaxSamplesPerBlock" gives the max number of samples to assign to a single PCR block by default. Asst: dsDNA should call for an additional PCR block if the count of samples to be assigned to a given block is larger than settings_dMaxSamplesPerBlock.

**Comment by evelynqi** [comment]
Instead of counting the number of conditions as the number of blocks, this new code finds the number of samples in each different condition and counts the number of blocks needed for that condition conditional on settings_dMaxSamplesPerBlock and returns the sum of blocks needed.

Current code: 
`=iferror(if(A3="","",
let(blocks,filter(BX3:BX,BX3:BX<>""),
"Blocks needed: "&counta(blocks)&char(10)&
join(char(10),byrow(blocks,lambda(block,block&" ("&counta(filter(BW3:BW,BW3:BW=block))&")"))))))`

New Code: 
`=if(A3="","", 
let(blocks,filter(BX3:BX,BX3:BX<>""), 
"Blocks needed: "&sum(byrow(blocks,lambda(x, roundup(counta(filter(BW3:BW,BW3:BW=x))/settings_dMaxSamplesPerBlock))))&char(10)& join(char(10),byrow(blocks,lambda(block,block&" ("&counta(filter(BW3:BW,BW3:BW=block))&")")))))`

https://docs.google.com/spreadsheets/d/1VJnNuNFptOyxiEBxLDk0Kx_GLgat0Uu6cKP7DIEjqFo/edit?usp=sharing 
Asst: dsDNA (AE2:AG2)

**Comment by bthuronyi** [comment]
Looks great! I moved it into Main and added an IFERROR wrapped for if the filter is empty.
