### ISSUE TITLE
Check through Asst tab columns and decide which ones to pull in and in what order

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#167]
Across all Asst tabs, we display various fields from the main tab for informational purposes. These are sometimes out of date or confusingly ordered. Let's look through all of the Asst tabs and remove any fields that don't need useful, add any we might need that aren't present, and make sure the ones we have are in a sensible order (not necessarily the same as in the main tab, but should default to that order).

**Comment by evelynqi** [comment]
https://docs.google.com/spreadsheets/d/14iyLETqdtZQeioG52ULeb9ee9v55LQikaXzbGCxZw4o/edit?usp=sharing

THOUGHTS SO FAR: 

General:
- [ ] I would delete strip pos'n for all the sheets -- I never look at it but that's because of our fridge storing protocols -- they are just not stored or labeled this way...

Asst:dsDNA
- [x] delete PCR template DNA (AD--you usually dont check and assume it is right; you can manually check if you wanted to)
- [x] Move scale (AG) closer to beginning (more similar to how it is set up in assemblies -- it makes more sense to have that in mind before you start pipetting -- you skim the numbers for if it makes sense before you start)
- [x] delete quant priority (AT-- if you queued them for quant, you are going to do them all anyway so why does it matter than some are high priority while others are normal)
- [x] delete gel priority (AY -- same reason as quant priority)

Asst: Assemblies
- [ ] standardize premix first or the other stuff first (I like premix first -- but I think it may be okay if they weren't standardized -- and instead based on whether a procedure commonly would use a premix or not) -- or if labs generally didnt want to premix, it would make sense to have premixing stuff after the individual components...

**Comment by bthuronyi** [comment]
> * [ ]  I would delete strip pos'n for all the sheets -- I never look at it but that's because of our fridge storing protocols -- they are just not stored or labeled this way...

The idea is that this is for the working strips, since it's supposed to go with the sort numbers. E.g. sort number 12 is easier to think about if you consider it as "strip 2 well 4" than as "12". We could redo it as "D2" if that seems better (we have the code) but I think it should stay in

**Comment by bthuronyi** [comment]
Otherwise agreed on all of the above! Feel free to make those changes now if you like.

**Comment by evelynqi** [comment]
> Otherwise agreed on all of the above! Feel free to make those changes now if you like.

Finished implementing Asst dsDNA suggestions listed above.

Asst: Golden Gate
- [ ] standardize order of premix components, extra components, water, etc..
- [x] Move scale and target nkµ (AX,AY) closer to beginning (for reasons mentioned in above comment for Asst: dsDNA scale)
- [x] Remove construct name (BD) -- I'm not sure why it is here... if anything, it would be put closer to the beginning
- [x] Move "Enzyme"(AW) before "µL RE"(AU) for clarity

Asst: transformation
- [x] move "Date transformed" (H) and "Transformed by" (I) to after all the transformation information (specific growth conditions, xformed amount, comp cell procedure, etc...)
- [x] Add "recovery media" to asst:transformation sheet
- [x] Add "growth temperature" to asst: transformation sheet
- [x] Add "antibiotic on plate" to asst: transformation sheet
- [x] Remove scoring plate items? (Date plates scored, plates scored by, colony counts, colony sizes, colors, score notes, expected color)

**Comment by bthuronyi** [comment]
All sounds good. Re: plate scoring, and similarly dsDNA / miniprep QC (Take3, gel), it probably doesn't make sense to house this stuff in Asst anymore, now that we have Asst: General where you can compile those fields if you want them. It was really a holdover from when Assts were about both construction and viewing data.

**Comment by evelynqi** [comment]
> similarly dsDNA / miniprep QC (Take3, gel), it probably doesn't make sense to house this stuff in Asst anymore

thoughts on the Asst:miniprep QC (Take3, gel)? @bthuronyi

**Comment by evelynqi** [comment]
Asst: sequencing:
- [x] I think template name (K) and primer (M) should go right after mixing instructions (D)

**Comment by bthuronyi** [comment]
> thoughts on the Asst:miniprep QC (Take3, gel)? @bthuronyi

I mean now I'm second-guessing myself, because it occurs to me there IS a task where one might assign sort numbers and then want to view the compiled data -- when one is actually doing gel sample prep or Take3. You would want to confirm that you've logged all the data for the rows you meant to work on. I don't know how often people queue sort #s for those tasks but it still seems at least reasonable. Technically you can do exactly the same thing with Asst: general but people may not think to. So maybe we should keep these but on the far right? For both.

**Comment by bthuronyi** [comment]
I can't remember what Asst: Sequencing's right-most column is for so I may delete it...?

**Comment by evelynqi** [comment]
Good enough for now..
