### ISSUE TITLE
Review for conditional formatting in user-editable cells

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#168]
Ideally, we should avoid having any conditional formatting in cells users can edit (green or blue header). If we do want to have it, we should be sure that's necessary/important. (The problem is that it gets copied and pasted around or otherwise messed up.)

Identify all conditional formatting on these columns, list it here, decide whether it's warranted and delete it if not (or move it to an appropriate/adjacent non-user-editable column).

**Comment by santiagochrist** [comment]
Gonna create a list as I go, listed in this format:

Sheet:
-
Named Range: **Color** // explanation // recommended action

I'd like to have you review the recommended action before we implement it. I'll let you know once I'm done!

**Comment by santiagochrist** [comment]
Oligos o:
-

- [x] Oligos_o_USER_query: **Light red 1** // prototypic entry consistency check // DELETE
- [x] Oligos_o_Sequencing_or_analysis?: **Light red 3** // very outdated queue check // DELETE
- [x] Oligos_o_Sequence: **White** // grays or like fades out nucleotide sequence // DELETE
- [x] P:P: **White** // same as above // DELETE

**Comment by santiagochrist** [comment]
A lot of these named ranges have the same gray-out from anneal/digest, so I've omitted some of them since they're most likely fine to keep. I've written it down once under dsDNA_d_Oligo_1

dsDNA d:
-

- [x] `dsDNA_d_Queue_notes`: **Light yellow 3** // mangled blank check, maybe consistency, many `#REF!` errors // DELETE
- [x] `dsDNA_d_Oligo_1`: **Rainbow** // many copy-pasted, singular cell/row formatting // DELETE; **Dark gray 2** // digest option blacks out entries for legacy's sake // KEEP
- [x] `dsDNA_d_Oligo_2`: **Rainbow** // many copy-pasted, singular cell/row formatting // DELETE;
- [x] `dsDNA_d_Input_DNA`: **Rainbow** // many copy-pasted, singular cell/row formatting // DELETE
- [x] `dsDNA_d_Num_of_cycles` + `dsDNA_d_Polymerase` + `dsDNA_d_Variation_additives`: **Light red 3** // garbage range checking some anneal blank inputs // DELETE; **Dark gray 2** // digest option blacks out entries for legacy's sake // KEEP; **Dark gray 2** // anneal option blacks out entries for legacy's sake // KEEP
- [x] `dsDNA_d_Digest_type` + `named ranges until Column AE`: **Light yellow 3** // mangled blank check, randomly pasted over ranges // DELETE
- [x] `dsDNA_d_Input_DNA_Vol` + `dsDNA_d_Date_put_in_thermocycler` + `dsDNA_d_Template_used`: **Light yellow 3** // mangled blank check, randomly pasted // DELETE; **Light yellow 3** // a check for the "!" symbol marks cell yellow, but ranges seem pretty random // KEEP?
- [x] `Row BC:BH`: **Rainbow** // many copy-pasted, singular cell/row formatting // DELETE
- [x] `Row BC:BU`: **Dark gray 2** // grays out cells if settings flag is checked // KEEP

**Comment by santiagochrist** [comment]
Assemblies a:
-

- [x] `USER_u_Construct_name`: **Gray** // randomly pasted "abandoned" regex check // DELETE?; **Light green 3** // randomly pasted "abandoned" regex check // DELETE?; **Light yellow 2** // randomly pasted "certify correctly queued" check // DELETE?
- [x] `USER_u_What_to_do_with_this_u_query`: **Light yellow 2** // mangled blank check with `#REF!` errors // DELETE
- [x] `USER_u_Part_1`: **Rainbow** // many copy-pasted, singular cell/row formatting, one is a color scale // DELETE
- [x] `USER_u_Part_2`: **Rainbow** // many copy-pasted, singular cell/row formatting, one is a color scale // DELETE
- [x] `Column BC:BJ`: **Light red 1** // some kind of invalid volume check? // DELETE?
- [x] `USER_u_Date_assembled` + `USER_u_Assembled_by`: *Rainbow** // many copy-pasted, singular cell/row formatting // DELETE

**Comment by santiagochrist** [comment]
Golden Gate g:
-

- [x] `Column M:X`: **Red** // Checks junction validity and marks red if false, but range seems a little weird? // KEEP
- [x] `Column AK:BD`: **Blue text** // Makes text blue due to some regexmatch, it's honestly fine // KEEP
- [x] `Golden_Gate_g_Target_nku`: **Rainbow** // my assistant sheet conditional formatting is here, along with random stuff in BF243 LOL // DELETE
- [x] `Column BY:CH`: **Red** // checks if volume in uL is less than 0, range a little weird? // KEEP

**Comment by santiagochrist** [comment]
Transformations:
-

- [x] `Transformations_Source_ID`: **Rainbow** // many copy-pasted, singular cell/row formatting // DELETE
- [x] `Transformations_Sort`: **Light cornflower blue 3** // makes it blue if cells in column B equal B3? kinda random // DELETE?
- [x] `Transformations_Actual_growth_conditions`: **Light yellow 2** // highlights cell if a specific growth condition in column K is specified // KEEP

**Comment by santiagochrist** [comment]
Minipreps m:
-

- [x] `Minipreps_m_Actual_growth_conditions`: Light yellow 2 // highlights cell if a specific growth condition in column V is specified // KEEP

**Comment by santiagochrist** [comment]
Analytical PCR:
-

- [x] `Analytical_PCR_ID`: **Red and Light Red 1** // mangled #REF! check across a range, maybe some old check for the template ID // DELETE

**Comment by santiagochrist** [comment]
Sequencing:
-

- [x] `Sequencing_Sort`: **Light cornflower blue 3** // makes it blue if cells in column B equal B3? kinda random, since B is number not boolean // DELETE?
- [x] `Sequencing_Primer`: **Gray** // checks if cell E says "whole plasmid" and grays out, assuming since there should be no entry in that case // KEEP
- [x] `Column AG:AH, AI, AD`: **Green** // mangled AG blank check with #REF! errors // DELETE
- [x] `Sequencing_mID_What_to_do`: **Red and gray** // checks for ! and A3 not being blank // KEEP?

**Comment by santiagochrist** [comment]
Strains s:
-

- [x] Random petty infractions, deleted them.

Other than that, I think I found just about every relevant conditional formatting. Let me know if you'd like me to implement the recommended changes (delete/keep) or if you'd like to go through them together when possible @bthuronyi.

**Comment by bthuronyi** [comment]
> * since B is number not boolean

Just noting that anything not blank or 0 evaluates to TRUE, so this is equivalent to saying "is not blank" but (1) we don't need it and (2) there's a built-in "is not blank" that's more effective anyway

**Comment by bthuronyi** [comment]
All implemented!
