### ISSUE TITLE
Transformations doesn't respect Assemblies (and probably also gID) manual Status

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#247]
If an aID is manually marked (don't use), Transformations still thinks it can be ready to transform if queued.

**Comment by ethanjeon** [comment]
In Transformations Status, added check for any manual "(don't use)" statuses in Assembly, Golden Gate, and Miniprep source IDs.

`
if(or(iferror(regexmatch(index(USER_u_What_to_do_with_this_u_query,xmatch(A3,USER_u_ID)),"(don't use)")),
      iferror(regexmatch(index(Golden_Gate_g_What_to_do_with_this_g,xmatch(A3,Golden_Gate_g_ID)),"(don't use)")),
      iferror(regexmatch(index(Minipreps_m_What_to_do_with_this_m_query,xmatch(A3,Minipreps_m_ID)),"(don't use)"))),
      "Source ID status changed to '(don't use)'?",
`

Added a question mark at the end of this status message, since some "(don't use)" statuses might be temporary/reversible
