### ISSUE TITLE
"Queue preps" status not updating properly

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#261]
Assemblies (at least) status "ready to queue minipreps" doesn't seem to be properly recognizing queued preps as of this version. Note that preps are queued for the 7 aIDs that show the "ready to queue preps" status.

**Comment by bthuronyi** [comment]
Debug copy showing the error:
https://docs.google.com/spreadsheets/d/14ya0qBmPaC6aUdvFqzbxYg43JsFkQXvu1DvKUDLr5Y0/edit?gid=1540456475#gid=1540456475

**Comment by ethanjeon** [comment]
Was due to some terminology issues in Minipreps status - will iron these out, but this change to Assemblies status captures the possibilities
`
counta(iferror(filter(Minipreps_m_Source_ID,Minipreps_m_Source_ID=B916,regexmatch(Minipreps_m_Status,"ready to inoculate|ready to miniprep"))))>0,"miniprep queued",
`
