### ISSUE TITLE
Primer (o) in Asst: Sequencing is not displaying past a certain row.

### ISSUE THREAD

**Issue by santiagochrist** [bthuronyi/CloneCoordinate#263]
It seems after a certain row the code is just not pasted in the cells, which means that there are no primers on display.

**Comment by santiagochrist** [comment]
Pasted the code down. Not sure what caused this, but it's worth documenting since it could (hopefully not) be one instance of many...?

**Comment by bthuronyi** [comment]
Most likely this is just because when the Asst sheet was developed, it had fewer rows, and the number was later expanded. It raises a different issue for tabs with arbitrary numbers of rows -- and we will need to address that, either through a script for cleaning up formulas automatically and/or by entering a lot of rows by default.
