### ISSUE TITLE
Better handling of dIDs and oIDs as Golden Gate components

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#36]
Currently, oIDs or dIDs can be Registered as GG inputs (components). This works, but the code for selecting a "Stock to use for GG" doesn't account for Status of these gracefully, e.g. failed dIDs can be pulled as GG stocks as if they are fine, and oIDs are pulled not based on Status but on column values directly. Spruce this stuff up, recode using oID/dID Status ideally or if not then Named Ranges, and if needed, add appropriate Settings about dID concentration or quality to use as a GG stock. (Or do we have some already?)

**Comment by santiagochrist** [comment]
Talked with Ethan, he said that essentially any dID status that does not contain "done" is not appropriate for GG, so I changed the last d filter to `left(dsDNA_d_Status="done")`. 

Think I need clarification on the oID, since every oID status is 'done' at the moment. The only time the status changes is when an oligos is being queued(?), and we'd only look at Registry once we are done with the queueing/procedure (at which point status is probably also 'done'(???)).

Other than that, added the named ranges. WIP code:
```
=if(or(C6="",S6<>"yes"),"",
switch(left(C6),
"o",iferror(filter(Oligos_o_ID,Oligos_o_ID=C6,Oligos_o_Order_date_plate<>"",Oligos_o_Stocks_made<>"")),
"d",iferror(filter(dsDNA_d_ID,dsDNA_d_ID=C6,dsDNA_d_Date_put_in_thermocycler<>"",dsDNA_d_Date_finished,left(dsDNA_d_Status="done"))),
iferror(query({Minipreps_m_ID,Minipreps_m_Construct_name,Minipreps_m_OK_to_use_for_GG,Minipreps_m_Date_purified},"select Col1 where Col2='"&C6&"' and Col3=TRUE order by -1*Col4 limit 1 label Col1 ''",2),"")
))
```

**Comment by santiagochrist** [comment]
**Update:** We realized that an Oligos might get manually marked as something other than "done" (i.e., hold), in which case we wouldn't want to use it for GG stock. Added a check to the Oligos status using `regexmatch`.
```
=if(or(C6="",S6<>"yes"),"",
switch(left(C6),
"o",iferror(filter(Oligos_o_ID,Oligos_o_ID=C6,Oligos_o_Order_date_plate<>"",Oligos_o_Stocks_made<>"", regexmatch(Oligos_o_Status, "done"))),
"d",iferror(filter(dsDNA_d_ID,dsDNA_d_ID=C6,dsDNA_d_Date_put_in_thermocycler<>"",dsDNA_d_Date_finished,regexmatch(dsDNA_d_Status, "done"))),
iferror(query({Minipreps_m_ID,Minipreps_m_Construct_name,Minipreps_m_OK_to_use_for_GG,Minipreps_m_Date_purified},"select Col1 where Col2='"&C6&"' and Col3=TRUE order by -1*Col4 limit 1 label Col1 ''",2),"")
))
```

**Comment by santiagochrist** [comment]
Final remarks:
```
=if(or(C6="",S6<>"yes"),"",
switch(left(C6),
"o",iferror(if(regexmatch(index(Oligos_o_Status, xmatch(C6, Oligos_o_ID)), "done"), C6, "")),
"d",iferror(if(regexmatch(index(dsDNA_d_Status, xmatch(C6, dsDNA_d_ID)), "done"), C6, "")),
iferror(query({Minipreps_m_ID,Minipreps_m_Construct_name,Minipreps_m_OK_to_use_for_GG,Minipreps_m_Date_purified},"select Col1 where Col2='"&C6&"' and Col3=TRUE order by -1*Col4 limit 1 label Col1 ''",2),"")
))
```
Changed the data structure from "filter" to "if/regexmatch/index/xmatch" simply because we are only checking for one condition, which is that the Status on oID/dID reads "done". Logic:

`xmatch(C6, Oligos_o_ID) // Take the Construct name and match it to all oIDs. Output: oID position.`
`index(Oligos_o_Status, xmatch(...)) // Now that we found our oID position, write its status. Output: oID status.`
`regexmatch(index(...), "done") // Check whether the oID status states 'done' (see below). Output: true/false.`
`if(regexmatch(...), C6, "") // If the oID status is 'done', output the Construct name, else output nothing.`

B and I briefly discussed whether 'Stock to use for GG' should check for concentration/quality when using GG stock, **but figured that the Status column should be the one to indicate whether a dID/oID can be used as a GG component.** As mentioned earlier, Ethan asserted that any form of "done" in the Status, despite warnings like "low conc?" and "gel problem", means that the dID/oID is still good to go for use in GG. 

Summary: Since we determined that 'Stock to use for GG' should only worry about pulling from 'Status', then future work should focus on checking 'Status' logic.
