### ISSUE TITLE
GG whitelisting sometimes doesn't recognize all parts

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#63]
Some gIDs don't have all parts listed in Whitelist column - unclear why!

https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAAAWr3j6LE

**Comment by santiagochrist** [comment]
The whitelist column reads from range `AU:BD`, which is a user-inputted field "Assembly, actual part sources." For some reason some gID rows simply do not have every mID part source listed? For the Row 256 / g254 example, there are no mIDs listed under the Part 1/2 source...

**Comment by santiagochrist** [comment]
Seems that the total for both rIDs and mIDs is updated solely from the mID part list.

**Comment by santiagochrist** [comment]
A possible solution is to define the total number of mID and rID parts in two separate variables. There was only one variable that stored the count of just mIDs, and it was used when displaying both things before.

In theory both rID and mID count should be the same since how could the user finish assembling their GG otherwise...but we can just tally them separately. The variable `total_parts` has been renamed to `mID_parts`, and every instance of `total_parts` in the old formula has been substituted with `mID_parts`.

```
=if(A256="","",
let(
mID_parts,counta(iferror(filter($AU256:$BD256,$AU256:$BD256<>""))),
rID_parts,counta(iferror(filter($M256:$V256,$M256:$V256<>"",$M256:$V256<>"(construct complete)"))),
rID_success,reduce(0,CW256:DF256,lambda(total,x,if(x="",total,if(regexmatch(Registry_List_of_whitelisted_rIDs_from_Golden_Gate,","&x&","),total+1,total)))),
mID_success,reduce(0,AU256:BD256,lambda(total,x,if(x="",total,if(regexmatch(Registry_List_of_whitelisted_mIDs_from_Golden_Gate,","&x&","),total+1,total)))),
if(mID_parts=0,rID_success&" / "&counta(iferror(filter(CW256:DF)))&char(10)&"parts worked before",
rID_success&" / "&rID_parts&char(10)&"parts worked before"&char(10)&
mID_success&" / "&mID_parts&char(10)&"mIDs worked before")))
```

**Comment by santiagochrist** [comment]
I don't think this is an issue anymore? I used a slightly different paradigm to grab all the rIDs and mIDs:

Helper Column 1 (grabs list of all rIDs/mIDs): `=join(",",flatten(unique(filter(D2:D,D2:D<>""))))`
Helper Column 2 (splits list so that we now have each individual element and not just individual cells containing multiple rIDs/mIDs, sorts it):`=join(",",sort(unique(flatten(split(F2,",")))))`

Using `regexmatch` and a word counter, I got the exact same list..?

<img width="1405" alt="Screenshot 2024-08-01 at 10 03 45 AM" src="https://github.com/user-attachments/assets/5c5cc75a-33e7-41fd-8123-43d9e806d891">

**Comment by santiagochrist** [comment]
I just went to row 334 (g332), which has mIDs that are not in the whitelist in (Lookup lists & tabulations). Checking off the GG as successful will produce a new whitelist with every new mID that was not previously there.

**Comment by bthuronyi** [comment]
Great -- sounds like for whatever reason it's no longer happening! Let's close for now and revisit if we see an instance of the problem reappear.

I did also look at the "Parts & mIDs track record" column and that formula needed some further adjustments -- made them, output looks good.
