### ISSUE TITLE
In Sequencing, "Assembly components with same marker as construct" doesn't fill for all dID template types

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#71]
If a dID's template is an mID (and possibly other things), the "Assembly components with same marker as construct" simply leaves out the construct corresponding to that mID.

**Comment by evelynqi** [comment]
1. The "assembly components with same marker as construct" in sequencing pulls from the miniprep sheet correctly. 
2. In the miniprep sheet ($BW), it codes for "Assembly components with same marker as construct" and pulls data from other sheets. I reviewed the code and  it looks correctly coded. If anything, I would get rid of the OR statement in the second LAMDBA statment since x would never be "anneal" in the "PCR template DNA" box. The box is blank for annealing dsDNA. 
3. Because the code looks correct, I looked at one scenario where it did not work. In these cases, it did not work because the "PCR template DNA" did not exists in the Registry as a construct name, so it returns "".

**Comment by evelynqi** [comment]
an example of this is m99, which source ID is a77. the parts are d109 ("CPB-36-444"), d42(""), d116 ("CPB-33-444"), and d117("pTHSSe_48"). These part names are not in the registry. 

That last part, pTHSSe_48, for example is not in the registry as a construct name, but pTHSSe_44 and pTHSSe_47 are...

**Comment by evelynqi** [comment]
Comments from B: look at how "g" is coded.

**Comment by evelynqi** [comment]
Update: "g" is coded differently because it pulls from "parts with same resistance as final construct" in the "Golden Gate g" sheet.

**Comment by evelynqi** [comment]
Note: I updated the code to include named ranges.
For those without previously named named ranges,
Minipreps (BW) "Assembly components with same marker as construct": Minipreps_m_AssemblyConstructsWithSameMarker 
Golden Gate sheet (AH): Golden_Gate_g_AssemblyConstructsWithSameMarker

**Comment by evelynqi** [comment]
Note: Formatting
Minipreps writes it: "construct1 / construct2 / construct 3 / ..."
Golden Gate writes it 
"construct1
construct2
construct 3
..."

**Comment by evelynqi** [comment]
@bthuronyi named ranges
Minipreps (BW) "Assembly components with same marker as construct": Minipreps_m_AssemblyConstructsWithSameMarker
Golden Gate sheet (AH): Golden_Gate_g_AssemblyConstructsWithSameMarker
thoughts?

**Comment by bthuronyi** [comment]
I think those names are great; somewhat randomly and maybe unnecessarily, I used a different convention for Named Ranges on all tabs other than Settings and Admin, which is:

Other tabs: e.g. dsDNA_d_Column_header_as_Named_Range_name
Settings: e.g. settings_dSettingRelatingToDsDNATab

So yours would be:
Minipreps_m_Assembly_constructs_with_same_marker e.g.

**Comment by evelynqi** [comment]
- Named named ranges Minipreps_m_Assembly_constructs_with_same_marker  Golden_Gate_g_Assembly_constructs_with_same_marker 
- converted all match --> xmatch
- standardized listing using new line per construct rather than joined with " / "
