### ISSUE TITLE
"Is sequencing appropriate?" in Minipreps logic needs auditing

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#72]
"Is sequencing appropriate?" may not have the best automated QC analysis. E.g. m3179: "gel and take3 data look good but shows as check QC data"

https://docs.google.com/spreadsheets/d/1xrwFnQ1eCSF4OkF8rvoMA-Njr5CS24l2QnlnsafiQio/edit?disco=AAABIlap3Y8

**Comment by santiagochrist** [comment]
Looking at the current code, it seems that if a single condition within the lambda expression is false, then: 
```
AND(join("",x)="OK", $Y3181="yes - color/phenotype CLEARLY match"), "Likely OK to sequence",
...
(iferror(unique(
{index(settings_GelCodingQualityFlags,match(AR3181,settings_GelCodingQuality,0)),
index(settings_GelCodingIntensityFlags,match(AS3181,settings_GelCodingIntensity,0)),
index(settings_GelSizeOptionsFlags ,match(AV3181,settings_GelSizeOptions,0)),
index(Settings_Analytical_PCRflags ,match(BB3181,Settings_analytical_PCR,0))
},TRUE
)))
```
the `AND` operator evaluates to false (since one of the flags being checked in `join("",x)` does not evaluate to "OK".

In the case of m3179, the gel intensity was set to "faint," which the flag under Settings marks as "Ambiguous." Since it is not marked as "OK," we get the Check QC data prompt.

With that being said, I agree that a quick look at the Take3 data and the other gel data show that sequencing is very likely going to be appropriate. The big question is that we need to figure out **"to what extent is a weak gel intensity made up by the fact that everything else looks good?,"** which may complicate automated QC check. One option would be for the "Check QC data" to have the user manually view the data and determine from their scientific expertise whether they should proceed, but that assumes a lot of familiarity with the content. Another option would be to only require e.g., 3/4 conditions in the lambda expression to be met for sequencing to _likely_ be appropriate.

I think we should talk about the logic in-person whenever you get the chance @bthuronyi.

**Comment by bthuronyi** [comment]
I agree with your analysis and possible paths forward! One approach that might help would be to use our historical data to get a sense of whether "faint" gel bands actually mean problems, as assessed by other metrics like sequencing failure. That can help us decide whether it suggests a greater chance of problems. In the future (v2+) I'd like to make that kind of analysis automatic and set up Settings that reflect periodic reviews.

**Comment by santiagochrist** [comment]
![Screenshot 2024-07-01 at 14 19 02](https://github.com/bthuronyi/CloneCoordinate/assets/173081947/40f963ce-1801-4e7f-8135-81b82b88d72e)

After a data-based analysis (shoutout CC), we have data that suggest that faint bands are not a great indicator of sequencing failure. As a result, we have changed the "Faint band(s)" flag under settings to be interpreted as "OK."
