### ISSUE TITLE
Assemblies "Queueing validity check" gives error if dID part not queued

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#78]
Assemblies "Queueing validity check" maybe? gives an error if a dID part is not certified as queued. Should it? Probably not, for certain kinds of queueing issues on the dID.

**Comment by santiagochrist** [comment]
I think I need some clarification. I tested out a case that outputs "✓ Junctions verified!" before checking the "Certify correctly queued" box, and adding an imaginary dID (i.e., d7777) returns "Junction error: check parts!," at which point the Status column prompts the user to "certify queueing!" 

Would it be that you are talking about a case where valid dIDs still throw out an error? Let's talk about it whenever you can.

**Comment by santiagochrist** [comment]
Talked with B, and came with this solution in the Status column (F):
```
countif(AJ38:AQ38,"*(don't use)*")>0,"part unavailable!",
countif(AJ38:AQ38,"certify queueing!")>0, "certify dID queueing!", // prompt user to certify dsDNAs used in assembly
countif(P38:W38,"<>")<>countif(AJ38:AQ38,"*done*"),"wait on part",
```
The `AJ38:AQ38` range was updated from `AJ38:AN38` to account for the status of all 8 parts making up the assembly. Since these cells pull from the dsDNA d sheet, we simply prompt the user to certify them in that sheet if they're not already checked off (middle line).
