### ISSUE TITLE
Sequencing status skips to "ready to mix" too soon

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#91]
When Sequencing rows have no oligo or type or date queued/queued by filled in, they can still be set to "Ready to mix".

**Comment by ethanjeon** [comment]
So far, it looks like repeat-entering an mID that's already entered in Sequencing autofills a bunch of stuff, leading to a funky "ready to mix."  Looking through the code rn...

Also don't know if this is already in another bug assignment, but entering nothing but a non-existant mID (e.g. m5559, as of 240621) causes an #N/A status rather than an actual coded status (something like "mID not found!" might be nice)

**Comment by ethanjeon** [comment]
Feels like a lot of stuff in the Sequencing status is out of order (chronologically) - going to redo it entirely and see if that fixes this + potentially other issues too

**Comment by ethanjeon** [comment]
Okay - as we just talked about, I'll continue with substantial rework of the Sequencing status, now alongside splitting half of it off as a new Queueing Validity check for Sequencing.

Besides my chronological reordering:
- move like everything before sample mixing into queueing validity (including new stuff like Date queued, and Queued by
- add a setting to check for low Oligo concentration
- a check for manual discarding ("What to do with this sample?" columns) for both miniprep and dsDNA Source IDs
- another warning for duplicate sequencing samples, but for ones which have already been submitted for sequencing (rn we only have one for those not yet sent)
- add a setting to check for low template concetration for whole-plasmid sequencing (currently it's a "30" within the code itself)

**Comment by ethanjeon** [comment]
@bthuronyi [Here ](https://docs.google.com/spreadsheets/d/1wq9HB1bwbIoiAi7TCaCgqyeieKxRiBZXsS2NWacdMCQ/edit?gid=1443880721#gid=1443880721)is a copy of CloneCoordinate with my new code in the "NEW Sequencing" sheet, right next to the original Sequencing.

The main changes were rearranging the Sequencing Status to be chronological, as well as splitting off most everything (up until mixing sequencing samples) into a separate "Queueing validity check" column (along with a column of "Certify correctly queued" checkboxes).  Also implemented some of the points mentioned above, and also addressed v0.9 issue #93.

The one thing I didn't address was "add a setting to check for low Oligo concentration" within the Queueing validity check... I could only find a static 2.5ul volume setting, I'm probably missing something...

And when comparing Status outputs (with the new code samples all checked off as certified correctly queued), I saw some discrepancies:
- some "done" samples now show up as "ready to mix" - fully interpreted whole-plasmid samples, simply with no mixing date filled in (row 1366, m2659)
- others ("wait on o" --> "ready to mix") due to moving things from Status to the earlier Queueing validity check or appending things like "redundant?"

**Comment by bthuronyi** [comment]
Some things I'm auditing:
- Warnings that could be needed after queueing but before mixing are present in Status - looks good!
-- The issue of "overqueued" is an interesting one there. The idea of validating _at the queueing stage_ suggests that previously queued operations would "reserve" the volume and wouldn't go to an error/warning state just because the queued volume goes above available volume. I like this!

`  if(iferror(find(index(Registry!$D$3:$D,match(index('Minipreps m'!$D$3:$D,match($A3,'Minipreps m'!$B$3:$B,0)),Registry!$C$3:$C,0))," Abandoned Complete "),FALSE)<>FALSE,char(10)&"redundant?","")&
` in both Status and Queueing validity check:
This is rather old code and we might as well update it to used Named Ranges and to use REGEXMATCH instead of FIND as we've generally done elsewhere.

`  if(counta(iferror(filter($A$3:$A,$A$3:$A=$A3,$J$3:$J=$J3,$AF$3:$AF="")))>1,char(10)&"duplicate?","")&
` in Status -- this might not be needed here too, and it would be nice not to always run it (which we will, if it's in Status rather than queueing validity check). If we just run it at the queueing stage, presumably we will catch it before the duplicate reaction gets queued, no?

**Comment by bthuronyi** [comment]
> * some "done" samples now show up as "ready to mix" - fully interpreted whole-plasmid samples, simply with no mixing date filled in (row 1366, m2659)

That's an appropriate catch of bad data from users. I think handling this kind of issue should be a separate process that we implement outside Status and Queueing validity check -- and it's not essential.

That said, for our data set, we can put something in the "Date mixed" field that makes sense to make the inappropriate status go away.

**Comment by bthuronyi** [comment]
> The one thing I didn't address was "add a setting to check for low Oligo concentration" within the Queueing validity check... I could only find a static 2.5ul volume setting, I'm probably missing something...

Let's check in about this live, I'm not sure what it is either!

**Comment by bthuronyi** [comment]
> * others ("wait on o" --> "ready to mix") due to moving things from Status to the earlier Queueing validity check or appending things like "redundant?"

This is definitely a bug for at least row 1277. If _no oligo is entered_ for Sanger, we don't want "wait on oligo" but instead "enter oligo to use!". "wait on oligo" would be if the oligo is queued but not stocked. Looks like the IFERROR here is erroring because the blank Oligo field doesn't match anything.

**Comment by bthuronyi** [comment]
> > The one thing I didn't address was "add a setting to check for low Oligo concentration" within the Queueing validity check... I could only find a static 2.5ul volume setting, I'm probably missing something...
> 
> Let's check in about this live, I'm not sure what it is either!

We decided neither of us remembers where this came from or what it means, so we'll cut it out for now and see if the issue re-arises in future.

**Comment by ethanjeon** [comment]
All above changes implemented into main CC sheet!

specifically, the old  
`if(iferror(find(index(Registry!$D$3:$D,match(index('Minipreps m'!$D$3:$D,match($A3,'Minipreps m'!$B$3:$B,0)),Registry!$C$3:$C,0))," Abandoned Complete "),FALSE)<>FALSE,char(10)&"redundant?","")&` 

was replaced with
`if(iferror(regexmatch(index(Registry_Status,xmatch(C3,Registry_Construct_name)),"(Complete)|(Abandoned)"),FALSE),char(10)&"redundant?","")&`

**Comment by ethanjeon** [comment]
:flustered: how to close a github issue
